disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - force_cast
  - function_parameter_count
  - line_length
  - type_body_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - R.generated.swift

file_length:
  warning: 550
  error: 1000
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - id
    - ok
    - go
    - URL
function_body_length:
  warning: 50
cyclomatic_complexity:
  warning: 11
